In [16]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')
from sklearn import linear_model

In [5]:
ecommerce = pd.read_csv('/content/ecommerce-product-reviews.csv')
ecommerce

                                                 review     label
0                      Law simply actually race it run.  positive
1     Fish help admit group gun real. Trial road tel...   neutral
2     Life standard score charge assume law.\nStatio...  positive
3     And perform edge data sea first. Something rev...   neutral
4     Animal interview huge activity some health deb...  negative
...                                                 ...       ...
4995  Man continue board. Mother drive tree actually...   neutral
4996  Could this poor a race senior free. Respond co...  positive
4997  Special draw sit conference end knowledge focu...  negative
4998  Write thank enjoy effect. Light home hospital ...   neutral
4999  Beautiful on tonight and. Million civil sense ...  negative

[5000 rows x 2 columns]

In [6]:
ecommerce.head()

                                              review     label
0                   Law simply actually race it run.  positive
1  Fish help admit group gun real. Trial road tel...   neutral
2  Life standard score charge assume law.\nStatio...  positive
3  And perform edge data sea first. Something rev...   neutral
4  Animal interview huge activity some health deb...  negative

In [23]:
LE_review = LabelEncoder()
ecommerce["review"] =LE_review.fit_transform(ecommerce['review'])

In [25]:
LE_label = LabelEncoder()
ecommerce["label"] =LE_label.fit_transform(ecommerce['label'])

In [28]:
input = ecommerce.drop(['label'],axis=1)
input

      review  reiew
0       2253   2253
1       1592   1592
2       2319   2319
3        204    204
4        207    207
...      ...    ...
4995    2429   2429
4996     934    934
4997    4005   4005
4998    4940   4940
4999     444    444

[5000 rows x 2 columns]

In [29]:
target = ecommerce['label']
target

0       2
1       1
2       2
3       1
4       0
       ..
4995    1
4996    2
4997    0
4998    1
4999    0
Name: label, Length: 5000, dtype: int64

In [26]:
ecommerce.head()

   review  label  reiew
0    2253      2   2253
1    1592      1   1592
2    2319      2   2319
3     204      1    204
4     207      0    207

In [31]:
model = linear_model.LinearRegression()
model

LinearRegression()

In [32]:
model.fit(input,target)

LinearRegression()

In [33]:
model.score(input,target)

0.00042113855282199797

In [35]:
model.predict(input)

array([0.9827584 , 0.97513854, 0.98351924, ..., 1.00295507, 1.01373354,
       0.96190466])